// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/mathnogueira/ioc/http"
	"github.com/mathnogueira/ioc/repository"
	"github.com/mathnogueira/ioc/server"
)

// Injectors from core.go:

func GetServer() (*server.Server, error) {
	userRepository, err := repository.NewUserRepository()
	if err != nil {
		return nil, err
	}
	controller := http.NewController(userRepository)
	serverServer := server.NewServer(controller)
	return serverServer, nil
}
