// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package commercial

import (
	"github.com/mathnogueira/ioc/http"
	"github.com/mathnogueira/ioc/paidrepository"
	"github.com/mathnogueira/ioc/server"
)

// Injectors from commercial.go:

func GetServer() (*server.Server, error) {
	userRepository, err := paidrepository.NewUserRepository()
	if err != nil {
		return nil, err
	}
	controller := http.NewController(userRepository)
	serverServer := server.NewServer(controller)
	return serverServer, nil
}
